keys:
    - &user_pyqlsa 0D35DDBD23509B6B7B2BB1F8BF79205BF790E004
    - &host_wilderness eb49cfa9e24ee89d8f29cd1cc79de855e3dc8e64
    - &host_tank 7e35b297ca18216c136c282cf792d8e8b9b0a050
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *user_pyqlsa
      - *host_wilderness
      - *host_tank
