api:
    dns: ENC[AES256_GCM,data:WZHdiQHohXrdD/X+n7ZuWprUSUrXgkGrJCEXYdcFn/Ma2OhPIkzN64vERXbomCOqGdQyb/Kc7WcOaZc90CPdqKmugf+gtpThPnH2YgoCE0MI,iv:lU+cyuOfZRDrLAYBmNV3kV5tz2x3ZRyo/gFli0a12Qk=,tag:z6f8kp74qqTSZEJA4w6E5Q==,type:str]
vpn:
    protonvpn:
        creds: ENC[AES256_GCM,data:EsVIZWs5gMHPxjVs40VYYy1BTMm1HpACX9VKRmzwmCMMDxEUaXTc8yYJYfHL79kuYqk=,iv:SPQLymjdeRtgW13E99ddmRUjo/brgjVT303QjY99Og4=,tag:SgdQJ3VfuyJq+0lQImh7Eg==,type:str]
        certificate: ENC[AES256_GCM,data:1qkyBJd+R++Cb8yshjdNVoU51tuFiL+RU1haWgvjoYwDJBODoZfDhKfKetbfo9kBExWxBpsR8QSXKTglKsgjuC0C5RLdSwRKV6yzd3hJLWOSVLnXFOsqGILbenYIUhylNGYPqEuNoTx4Vb4rzm3U7VyyFCgr1VsfJF8ESIpDKQqZNe/aDy/OBX/aulV/KGxmsAzsy1HwAT4JIwHZrYe0DKO8CpqYmpI2AIW8PElHhhSOrC+l4B/gjR0zgOw77nkIlpq4tiMi6pGDRqSb80cTQ8ACUUOyTt7V57hqmcqnd0WOY0ieiCfbkfQzAeP8ITCuKG/ww/WFBRizcGA+J/xP39Vu4Sr5XpWn+mudRYU62aIHBNqjwjbZTwibpW2LKP5OahPAJDvwomqFF9L1VBFB/GFthaR78WnlxnnSJAADIoSwmmP/E64bIuuMqtIJAAsfadIbM1K9KKlXEODW+uGHtJecYMnyBU/CIrKyA+qYRdpMWXGVVtRtIlnteZIqu4qMKI5v7dmKgpm0XDhPHR0JklMY/PKrBGpZoN1bq3Ubc+mhJs+49OVyTmJeCJbttEyZnRXPpQc+45akiPDwgGGTE5MAn389Oj0AxLF88k14hakpJCUmK6YufgKdY3h1PH08DYIAchhUZv+eF2ZyvcJA9d/aSJMLSwqZXVkJqVTqWekYe7Pt50a0GgwoXPBzbbvla0MmryP8hM+8u2erPRiERjLdlB8pMBddNMXKjmzbgJliuR46kqRZCg1oUT8deHHBzD24NxXGTdO6SzOWBbud2bOB9VHcYtMrx2dcCG76Mr67jR1Vjmn6S1jHwlSRdevim/8UIMxCDb0dpYS51qzLX2LaZc1DXdGlpcq1bIyqVtlOlT3q/XF+WQES3j47piS46jFbMleY5f0OLXdBwRSDxNBR4nYQdQkMCqnK3Rq4K8YITIkKfUtrLoQngYuUy2PRGQoRr7XOnSNDOooCglZau28NdsNETtuWPNSF57TrYWp3CwIiXI3IsUA+M8JV6HQvUOCo631LlREhXSqsRVQWOYrtgl+O15JQ1A/mmGr4cE+ZbD+U/wDayMk9H38vbhswRzk4PJMwplxp+DxH2mTeCcjJ04ZQ1HPg01+ntaouN1mXD/S5mAePGJZ29axXwi7wUOpKWBAHOpIGUXZd8svVv9qCrqEX74rutllva116kfNO70HV9APwZlAl1nqrICoDw15pd46sztn/6A6vDGns7qODIYlOBP0tIJLuFeaxuC/huc31PIDnTw/HiaOkj43dU1MtTMpZlFSdB2gKFy4lx1E7mLYd6yvUq49V13x7s/wCU9SabGtQhy8hXVztsbki4wgzzfnU5Li2zETyMOxpUNBnycQWk2d7mSDdj5GgfKPg2EQyTaSjYI3eJMBkZBHHhxPynYWugJF1mwm/qtWtBr3JwCsS32TutUbzkvcXwpNd3+l5mFS95iY/R8mzo6/Oc/W/AXW07ISkPs515aHuobZVSt4ipjM6fjH7Y6FdyzU9EUN4JomO4q3jT/Ms+4ws0S1JJGgQdDe2qBfFaMM8uDzM50872phgVycsbdLXrinQ/7dGVD9Mpu75XWlfKB0l4QLAwOFQJYNfFKogHQ5MOwDisAlIqFTNi73xpTfj3mc5ILdamWcymP/DgMEmxtJrBdJmqK+F8pjU4gCZhpskJgU7GhonogZgDf1KRWNZ4BN2fQ/B6WNkMXDjxXRcxofwwQevFhtoNofN2iTKU7IQd4gKHj/svSd0VX3VQPCYrOqZGn0jIbQWjP+Riiev4Qer5Bdgqt11UnqH5RCT8/k3Dz2V5qJdmw1KHF33bw3/9AoPRVEM+LMXP8S3QxEomQRtYYhMeNMgb+8BcHKL4VCIHZSCNbZFRnoeghCvDbhUHgpk1wGIg5yxZYLiOrMFozQV2XT55kqLj4ZxhvtPjTIqpa6lQ9+UAgSE5LNoXc5KPReRuARkuFA4dP4dHSah+G4E1HdzvwpJjvYCOAxBgQfK6SW7wXmFBKkdwstYBUmISBZ2iW38AvN8RdhPSNAvASy4Z36kkQIl9W0g4XtaSwH8BaC+bX2HQCkgikpgDPoA4kNA8puai6AdvdUhge4MqGwEn/UVoZtJW5OBIHIWMEv14bvNLOUvIn7N2FfIfLk09p9Bx9YVUZ+z23Dt46Pcgn+Qb7YWSYVR0ftfGNRNQePQP7NG0Fa/o7EzoJK4gKpeM8uh6VA5i8xPcpXMdN7+TukOl3MZrqAKFAAWo9z9JzUGmn3pxCxcCc5xv0o6BAxp6voDEioBDbLCr2X6Qjgtg4Ib+TwibxjtOp32Nt2C6LXAsjg18wT6iiiWiyukFu+z+DuuRFpD78AaeM5qiiOxDcJ+UsYpssCmJa7Anbko0VQUPjT8V5j00xsgB/6l424KahLr5YLCZsVxy+Y/pystYzgQG3dTjFSq0BFm3wWE84ezcagyFZAzDisC38gYQ8VSPQhF8mFIPUPyhXspXxgcvCeaOG8GDr6wzIVHsWnU3icgrkPExyIcY8tYcAgxckXgmg4qwF3Bxv73kzzBhClZ4+pr5/dFXGM9M+8X1dj1jxL0Z/KvN9FP+cSTKAtwP0oOWjZQ6mZ1Y04KvELjZ6kAQ1MXkIHgoVqNqKhMpiIO2sNcPF/nIPbtDLlJIj3V79lWVjaR5H+K7VZy84I=,iv:qVuLAmIQcjjg5KRY0CT0zPAsHVixc7laNoKLirrqZl8=,tag:VWqzoDkfDNBnEw2gSdtjYw==,type:str]
        key: ENC[AES256_GCM,data:f0WjHKE/H6m16iLQma0D4zYtxf2mAMeXhJZJP8gjX+Poeekddq1qheOw42XdFXcJqSmEsYMQnRqRYYBMON1YeNcPzJPMLAlJpzHwyKQEkfLe9GCHiyxZUnv4bqPiTumQZsEmiaAJBJF338u/NbbhKfNcNTFET6qYWU46jAbDbrI4OIeFoaB3K0i0uK9w6jmsy0sGVs73aX+lKg4KqHkUTQKyYTaIgMKXq5vOND7HT86Z+bhdpFBaRtR5sh20EuGltKjlBf+8j0PlO/M/vpy63vJhuotD73lhYTKZBAPg75MfF9B3nY85rdsWQ6P02K5u4Zi+k/XNINZTpIyToYi8F5M/axHs0uvqRgINe2oPyJvl/IuR+mmKqMYO3gwvUpV0RfIh+euGo8a7EVb46EOfmasfRERpWM4DW+6cJQaAhq1BuV+R2OyWCxiBeZ3eg5bbBxd0fehNJ1g30cGoVTk2VzOXoWC23hCqJleFVflUccRYqsw8eeDK6IsZCCq1a0FvfQIg5nwY8E3kBB1eiI2SqiUF1iDUpnidTNXWCFdymO4FMWwEVpKD0WzHjbBOISt8EEjf5YDU53rNlNBqlagB8eKbXMYhZSJBsFXQmeYzY2tJUXRjUZXoLbO2BMaqcV6jB4pBhprOcd4b9ZYYkyG1QgpF8+OWhUpt6rFOcfEi9f9ug2R7wx7YDJAy84P/nKxEfD6cSunUwqgwSicolLFv/nLE6BWBczG4AQ6OfM89s1/kbu6nYEEzsJrvItiLOQOqPfr59eNLdEzCj30REG43f/LQWpZVt/X5Ml0=,iv:j7AKfmtyjJkl1TLf5Uz4Paw0FwYrOa12j3GUbdhAUoA=,tag:BRLx0QU/ZEa6c2Gr21iM8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-05T22:28:42Z"
    mac: ENC[AES256_GCM,data:nkLnfbC7ijg+D0Efgmg1UCkzGmTWS5qYLWuVq6jX6LEpFBo8ooGjO/QTLHSNI7sOU3mLyLia/cEgIoIztYi7fY9A6OZTkopEwy7DzPdpQIk9K9aT3SEnOn1mq1H3A/FOF59X/a7Z5CWRTJAkK86jP5SNI3NgzTk4VXWBWH3kd9s=,iv:GO67zOnxWL4BUK1jNe4qTDcsZCphcERjsGYNGgTDfaw=,tag:mZJHOVz8l9jqJ/xr/ECFXA==,type:str]
    pgp:
        - created_at: "2024-04-05T22:46:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D12Wx/ozRU8gSAQdA9C2wP4qM7ikB1rGYYC/2Zw1rxkzt5R2DMdw4NKTfNnYw
            qIekpwbrc/LjobWijWklm33DfN3tkIb+ZT/tDpAdgpWYCO1+Q8XhqcR4W4VjW5gX
            1GgBCQIQtS6RmjasvzixKT1CMwHd8YRmOZJWsV2HVavr0ymlQS6EfiddR/gmeljA
            azKfdVxnfii2etgUyzZIa+/sWg8qwv/OxlsXznRoqea5tMwEkRk32UV0w1chwMEt
            MNOtx5+49kFodg==
            =8b1O
            -----END PGP MESSAGE-----
          fp: 0D35DDBD23509B6B7B2BB1F8BF79205BF790E004
        - created_at: "2024-04-05T22:46:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8ed6FXj3I5kARAAtw4dD9D6VYZWpUP+Uc5A8wQS2dsOOwvz/Bq9+EG5zA08
            6dQxop39PtZNSLzCVtlpR97zMGCilfNAQ0QVlAY8B/Xh0zziQpbDKBhIX7wBX6gw
            nPTOTkkb2eAoi3aYZcwPTX9N9x4InHk4j949s3gfotnCgNnbhKQwHyqacJ8T0oBR
            M1BoAITn61lwUDlm8vFhIDP5krsbNl6lMmlewA19pvxzIZBXLLbZHwvazcJNw871
            OAb+nONm+ofE95EJ3vSR5fSY4R9phpKotTltp/VCwrfzpS8LVp3veZk1nhZ4AHXf
            ZNP5jel3h5eKkb210EY6VijUnQToNA45GN03GcnadkF6VETA0oAtOOsH/nYK37SY
            VlDF2FzQEPyh0NyozEOYhgSf+6yG8fASE1qP1YfcM2O4f0Bk0MtspEA5YwEj7p0z
            Cb03w+YXWdCiHU0/GL2JyDhtzAdLPCC86hUIVepgl8j3zx5zzMCpedmR4rjCxrh9
            9DJSz/+AlP9Ikrkv7cFrq5A9AZa2kswDtQgh3R1v3X8vBMh+ofD7bW3wkfc6RI7U
            A+PhJOpdCjxcEqq7w5VJQNTHy9k6+zwHpdHKLIDt4hXARXJirLT5I0nGH0QTWYHp
            PsbVMJeJ5shSowhx4Rt05Ll3K3VhipZOKmCmLFGk/8CiY4WkN27bx5h7dPKJ3KvS
            WAFyYuxSOBlfdvjEjasxDtJ4AWlpcTgBAmwIMFKUFeJhx4KjbUAg2xHsQkpAfEGx
            eHiQb7Ie6EVZgdMesFoEOeSQdz0duPxdEZNS7NIWvoqxrPRBQHFus7I=
            =9RtO
            -----END PGP MESSAGE-----
          fp: eb49cfa9e24ee89d8f29cd1cc79de855e3dc8e64
        - created_at: "2024-04-05T22:46:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/eS2Oi5sKBQAQ//R44yAxNyaROhwQAJvT+XdQEMj0vEumVE8LwivjEKmwSU
            Bw4IfWB4el6FKyRVcR9QRcmX5l0499UYR/QSqU5u8R60QhZfPKufy6VMJFSrW3Uw
            Di/j6VvGT3XkG5pu5e2ylgQRsZC9NatQ3UJOsUqgQCv15BRq1MDyUyoV0xCq6lOO
            viQMmgzrPUdZ3+946bD58z0a4xOYm4qTPaVzdEODKfA+3vu/DwhNj6moxkmdkgbf
            8pJrSRMgemZV562XOXZC727sHv5s8I+DZVie3hzuC9fLZnEPYRafp1LxguSTuVJ3
            ZHqzdTW8DFUhf0anEYlgGH/ynhMc3qYTUWuO9AXHrnOci/3pp8aXHvwGL7mMsR3X
            2tcCMqdhYeXxhEtlQhddH2oo7ewAcWl9g54686zJSWOpVTJQiefJYGOHTFiEStsJ
            JOJXy+JVXKX0wzCvVLSaIrt6WlGVDTCO07/wgHYGFyKmgX9zICSbfnkjjJ9rAT4h
            jXuAYVQYXF9xUfoAikRWW3RpzhkcNIKcuxh1rHbSHdD3q3/xCYjs3eWntv4yiN6v
            IP+AWk+RFZcI3FNu+Huq9EiavY0TVDgHR7t4GbA3BzsqU9q6zgCxuK43ckgyH8wi
            Yc/s9tC0HBN555diLMdhiWyu39Uop0dQY0nzpKUwyRJnUC9YO48wCIKCBrgjU/7S
            WAG/OA3Vbpvc3NZMezT6X9M+RG03tPXm/MeeYPr3bZ+Tqeqrs1FoBH4SRh8p2mZq
            0STEbELfPNcgFrcb5eeggSl6qRWrhMv04MlLpGl0D1SIRaL1UvBkjHQ=
            =rUTW
            -----END PGP MESSAGE-----
          fp: 7e35b297ca18216c136c282cf792d8e8b9b0a050
        - created_at: "2024-04-05T22:46:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAw+pupFfzjloARAAkmjlgSAiHTPfPOfkk7ldMf1VmHQNq1Ftxn80FhTH23Ju
            2JzbWJ+LDsRp8KkhIP+yFkQC10DOQCBw1S64vYSMGZjZIBvq19MqhaYJGMpI8BrH
            v7tP14F+F97HBlYTU7dhvQAbacQ6uM+R/DREjkqkvTDd6UT9rXTtw9HV1sQmnhbl
            /wBWbnvVElh9r2OOTGuUlBbSxbjtOs0xNVZCGMWatkz5Tek+FK6egbLd5tCKjE6G
            1EVtOC6DlDB35lwXEWgIlgN5257DxWYgiu/r24FzRnnIo+oVh/fX5tx3493dbUc4
            LFJ6usruySu1kLrF5xR1Q0ABFjafnmGdWnKRBMFEgYVIwoa5jpBXpB5LVjyrVfad
            OkUa3QFMk8rWXip/v3vQ5Im1PmQnbnVk61iPRDw+4kKthZA/3Le+4NIZ9PjCsGqj
            zPPjv7NuM3dcrB4tfVBxKHvSo6ako0SoXxB689ZMRj5QUJxF2NuAdELZs695d5gR
            TLHs79EX2Czpvbu1bV51bwxiuUqLKQDRbSVstYsdeeT5snPQdosOp8sazuSrdvp7
            Vtewxlb13pgz4vOfYPccYYNRrNzwN9zMFbC0I9I/9i9aTv8O41H90r2T067G885t
            4gTAHqvr4WPHk17sPrzEHctfIxSGS3NV6sWS1rSO1FYdjm9PCIkEA8TiC+KZ0JTS
            WAHeKU2KsSnTu16eOgOxkbmwCtt0b6DJ0WE47Gw303u1HtPAkVcLyXJmlMmx/wlP
            RdaykE/pv8xwfoctGu/dQQ696/foetaThIXFqynWFFvDSiUmmHU79gc=
            =BcVX
            -----END PGP MESSAGE-----
          fp: b75be913583f322dda6a07100fa9ba915fce3968
    unencrypted_suffix: _unencrypted
    version: 3.8.1
