example-key: ENC[AES256_GCM,data:gOYhlMfM/gZzSMDEeDuIxqTL6T45OEbuos0=,iv:d+kllh9DALklNITOEKwdeWfvz6cCNJ3vsg4yBpvvMK0=,tag:uWN8xUeqc5yPQRPfQvevgg==,type:str]
example:
    nested: ENC[AES256_GCM,data:0sQXCMEl8GU=,iv:X/rSmLR4tqxPNxw+jnUHtuEkFQU/wGi2tRr7lssXODg=,tag:nXVMCQXK01MMt3v6AcqK/A==,type:str]
    another: ENC[AES256_GCM,data:Wd55Kjep,iv:t8YS4Ij/e/YYc2GivYij2jRXtXQiUEDxYRM6QWoEd2Y=,tag:dtbZ7d1cfTJFghDg/alBkg==,type:str]
api:
    dns: ENC[AES256_GCM,data:WZHdiQHohXrdD/X+n7ZuWprUSUrXgkGrJCEXYdcFn/Ma2OhPIkzN64vERXbomCOqGdQyb/Kc7WcOaZc90CPdqKmugf+gtpThPnH2YgoCE0MI,iv:lU+cyuOfZRDrLAYBmNV3kV5tz2x3ZRyo/gFli0a12Qk=,tag:z6f8kp74qqTSZEJA4w6E5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-14T21:29:32Z"
    mac: ENC[AES256_GCM,data:g1jtjzjmGuhucSHTuOLnH3HzkC8Thmx666qQJXtLC61S98AgiKD28BYRDuLqMtDw6uIP64h7iGlm13Q195kZGvJT6sF/vqGSURAeV/5jFcSJYqQHzAB8xZ9vYzglPYrkpEeol7E7kfR7dhocyoCljyDOa4UAcgemNd7nDb6kSL8=,iv:m6+aFZUIaKjSiQDhDWJ+Geb4ZFnu7mLMWVuXRNZsMiA=,tag:MvZnhQYvwj/fjGBp0JI8cQ==,type:str]
    pgp:
        - created_at: "2024-01-13T22:47:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D12Wx/ozRU8gSAQdAPXdSwEHBTilf5KBNHOJlKQ8kaB5eX5pVeP+TCxBy8jsw
            OAYpRD7hpWVmM3DgwOkUNM90cTiTTLqAp1PRQZN1XLuuvzLEOsTwt4HDrtH19HVU
            1GgBCQIQBVi+225XXEz4p92PxnIwxbnfE10YwzUR1koX8xdIymV4tbO6uWyDgnhd
            48gDo+SiHMgBYC083QYXeObCwJ8B5yNJhvNdq8X/2at1Gnf8nnm4IvbLrLocjjJ0
            6zpoL8rWKZeiyw==
            =dIY2
            -----END PGP MESSAGE-----
          fp: 0D35DDBD23509B6B7B2BB1F8BF79205BF790E004
        - created_at: "2024-01-13T22:47:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA8ed6FXj3I5kAQ//QDJ3GvgC35bVpDHgh+OWBU8GtJdUwpxzqV2TFKj05fMC
            ZNxnin+BxV8sRLmMZqedrGDVbwLHtRrsLX035IDqoApsnLgEc1jnqfivGlbbZlAz
            kvEz4dJJujlW3NNmouzn5FohP2PB7lxqzbTa5dhhRBekzifKrwyKJBAZHr1ZkHb1
            MNZE7hFazKnL37SNGoTEqLG4LeMbXTOn+EC3GpIPXOCdfVwa4fu2+DztwKxpI2Ev
            zzuAPF0baDX6TtoUzwmXt3H4buBG9CC1qgeV1ycFK6YqSAR/GJiC8oEPMq7i3Dqo
            AK+RKbgqGdwdHOYWNR7XuxcGz/wMCKlJ85LwfedslJ7K3dWIJJQjkUhrFu58JGXg
            EF4s1T1G9vMp/ohMNxCqlFmqHUddMjVa7JuDp1qKVGMYEbYNVoizYW6GCEJClEYg
            jn96wXF1Su5xOoMunPV8gLHZd/Q6AdVUmuqN0k4eETifszGZbpd1lGUfNEyE6Lm3
            eEafuemJQEnY/vmB9d01j3uvc5Prt5fn3BY3nko8CQ9whCMpv0KSR4i2r4z5hZQE
            arwFZNUHChnAMgwEyuiNoGoW+9G/2N4fhaMKowy2HeVKyt32NcphqN4iw09TnyyB
            qPDy2T3IxEAgthK/IQG2KFnPNfuXKDZXNmBJOOUJgQdDve6eUKhg07i7M0qtA4LS
            WAGFR5aN20DZF/RnItA5V9yklHFRxLmSxEFhxrJ6LaY2or4VsgMD9GYDULPVUQoM
            3fv/absrJfd215rDEENZvnWhevX/afE77AzaEypguLCgmQ9yCyiAlQY=
            =e8sr
            -----END PGP MESSAGE-----
          fp: eb49cfa9e24ee89d8f29cd1cc79de855e3dc8e64
        - created_at: "2024-01-13T22:47:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA/eS2Oi5sKBQAQ//SLftCkVThCH3SDfT4wm+rf/WUV2QfyWHbriW8KV2Evpt
            dcHsBBu43lsXJJ4Pa0QjIZcQ7El3KtBhFAQ80/O1eExoic1sXj+SV+XtIDjT7m0s
            R2gKUDLlT7pt5COJ/oX7vbOWi2UW6BNhNHbI/ZucMZ9jl2ae26OnLVwpSuRLrkw+
            1Z3dD/Hx5e5G+vghOL06OL18YKN0d952FCx96PIW5r9d05CkIXl3PMtBHRHGsbNH
            P+Cv9n+2cd2irjRMBiyuB+yluITpLH/rAj9nqvkLHXnOV1IWILRTBAQrQIFWdTTR
            KisU2+KDUAj9gPgRwDF15miWVKZvy4zxFbYC4AZsOH1nIQtPCnbxD+aiIH/lVjCl
            /9qyQa8/30w4Md3P/uQW6KVM9duFNQ+VyAhh6Q931XnovSZmX7TFwEF63l7O4KY5
            Kqk46U+GC0O0wtlzgrNdECPsQqy7JU/doxUOfp3IFs7pav+5ITFLa7JugtuTGA0N
            vbfjVZ5LTtKRox53REgc/riQ8jxTMgeGhm6i0F9G36RoIZpovXbYPtIA27a2eJ9x
            v+wawtRZyDzKHWl0ZExHcYc40o5pFqM6xn6A6LvVCfUHsRc6+3waSeoo6HX65Zxj
            wPpsEcXsluDcfUFkC0z4AAt39OXkMtg2NPcLmkjOEGYSeIPoiEjJc+0/FZEGMHXS
            WAGP4fIzBjXFdXOi2BWgHNe5lF94kJAj/FDIS0gcVUjyqmqd8dCdZPLQlB4+GM51
            GMl/jgHt6e+U71Z2nBfQrEN1QSQdopybOzQBZlDx0MMtJ+pcByTTv6A=
            =kG+5
            -----END PGP MESSAGE-----
          fp: 7e35b297ca18216c136c282cf792d8e8b9b0a050
    unencrypted_suffix: _unencrypted
    version: 3.8.1
